const questionBank = [
  {
    id: 1,
    type: "single",
    question: "LabelMe提供哪些类型的标注工具?",
    options: [
      "矩形框和多边形",
      "点和线",
      "矩形框、多边形、点和线",
      "以上都不是",
    ],
    answer: "C",
    explanation:
      "LabelMe提供矩形框、多边形、点和线等多种标注工具，选项C是完整答案。",
  },
  {
    id: 2,
    type: "single",
    question: "在LabelMe中删除标注形状的操作是?",
    options: [
      "选择形状后点击'Delete'按钮",
      "直接按键盘上的'Delete'键",
      "选择形状后按 Delete键或点击 Delete按钮",
      "无法删除标注形状",
    ],
    answer: "C",
    explanation:
      "在LabelMe中，需要先选择形状，然后按Delete键或点击Delete按钮删除。",
  },
  {
    id: 3,
    type: "single",
    question: "常见的图像标注结果导出格式不包括?",
    options: ["JSON", "Pascal VOC", "CSV", "XML"],
    answer: "C",
    explanation:
      "常见的图像标注导出格式包括JSON、Pascal VOC、XML等，CSV不常用。",
  },
  {
    id: 4,
    type: "single",
    question: "Doccano中标签集的用途是?",
    options: [
      "表示软件版本",
      "表示标注任务进度",
      "表示标注员用户名",
      "表示文本中需识别的实体、类别或关键词",
    ],
    answer: "D",
    explanation:
      "Doccano中的标签集用于定义文本中需要识别的实体、类别或关键词。",
  },
  {
    id: 5,
    type: "single",
    question: "图像重采样不包括以下哪种方法?",
    options: ["最近邻插值", "双线性插值", "双立方插值", "直方图均衡化"],
    answer: "D",
    explanation: "直方图均衡化是图像增强方法，不属于图像重采样方法。",
  },
  {
    id: 6,
    type: "single",
    question: "数据组织与管理中，通常不需要做的步骤是?",
    options: ["创建文件夹", "定义分类标准", "移动数据", "重新编写代码"],
    answer: "D",
    explanation:
      "数据组织与管理通常不需要重新编写代码，主要是对数据进行整理和分类。",
  },
  {
    id: 7,
    type: "single",
    question: "数据标签拆分不包括哪种方法?",
    options: [
      "基于规则拆分",
      "借助机器学习技术拆分",
      "使用数据清洗软件",
      "使用数据可视化工具",
    ],
    answer: "C",
    explanation:
      "数据标签拆分通常使用规则、机器学习或可视化工具，不常用数据清洗软件。",
  },
  {
    id: 8,
    type: "single",
    question: "数据清洗时遍历标注文件的主要目的是?",
    options: [
      "检查文件格式",
      "提取有用的分类和标记信息",
      "统计文件数量",
      "删除重复文件",
    ],
    answer: "B",
    explanation: "遍历标注文件的主要目的是提取有用的分类和标记信息。",
  },
  {
    id: 9,
    type: "single",
    question: "LabelMe默认保存的标注文件格式是?",
    options: ["txt", "json", "xml", "csv"],
    answer: "B",
    explanation: "LabelMe默认将标注保存为JSON格式文件。",
  },
  {
    id: 10,
    type: "single",
    question: "目标检测常用的标注形状是?",
    options: ["圆形", "矩形框", "曲线", "文字"],
    answer: "B",
    explanation: "目标检测通常使用矩形框（bounding box）来标注目标位置。",
  },
  {
    id: 11,
    type: "single",
    question: "语义分割通常使用哪种标注方式?",
    options: ["矩形框", "多边形/掩码", "单点", "折线"],
    answer: "B",
    explanation: "语义分割通常使用多边形或掩码来精确标注目标轮廓。",
  },
  {
    id: 12,
    type: "single",
    question: "下列哪种工具主要用于文本标注?",
    options: ["LabelMe", "Doccano", "Praat", "Photoshop"],
    answer: "B",
    explanation: "Doccano是专门用于文本标注的工具。",
  },
  {
    id: 13,
    type: "single",
    question: "Praat主要用于哪种数据处理?",
    options: ["图像标注", "音频/语音标注", "视频标注", "文本分类"],
    answer: "B",
    explanation: "Praat是专门的音频/语音处理工具，常用于语音标注。",
  },
  {
    id: 14,
    type: "single",
    question: "Pascal VOC标注文件格式是?",
    options: ["JSON", "XML", "CSV", "YAML"],
    answer: "B",
    explanation: "Pascal VOC数据集使用XML格式存储标注信息。",
  },
  {
    id: 15,
    type: "single",
    question: "YOLO格式标注文件后缀一般是?",
    options: ["XML", "TXT", "JSON", "PNG"],
    answer: "B",
    explanation: "YOLO格式通常使用TXT文件存储标注坐标信息。",
  },
  {
    id: 16,
    type: "single",
    question: "下列哪项属于图像插值算法?",
    options: ["边缘检测", "双线性插值", "灰度化", "滤波"],
    answer: "B",
    explanation: "双线性插值是常见的图像插值算法，用于图像重采样。",
  },
  {
    id: 17,
    type: "single",
    question: "数据标注中IOU用于评价?",
    options: ["标注速度", "框的重合准确度", "文件大小", "标签数量"],
    answer: "B",
    explanation: "IOU（交并比）用于评估标注框的重合准确度。",
  },
  {
    id: 18,
    type: "single",
    question: "命名实体识别(NER)属于?",
    options: ["图像标注", "文本标注", "音频标注", "视频标注"],
    answer: "B",
    explanation: "命名实体识别是文本标注的重要任务之一。",
  },
  {
    id: 19,
    type: "single",
    question: "批量标注处理的主要目的是?",
    options: [
      "提高图片清晰度",
      "提升标注效率与一致性",
      "增加数据量",
      "改变图像尺寸",
    ],
    answer: "B",
    explanation: "批量标注处理旨在提升标注效率和保持标注一致性。",
  },
  {
    id: 20,
    type: "single",
    question: "下列哪种格式不适合存储图像标注坐标?",
    options: ["xml", "json", "png", "txt"],
    answer: "C",
    explanation: "PNG是图像格式，不适合直接存储标注坐标信息。",
  },
  {
    id: 21,
    type: "single",
    question: "人脸关键点检测属于哪种标注?",
    options: ["点标注", "框标注", "文本标注", "音频标注"],
    answer: "A",
    explanation: "人脸关键点检测需要标注关键点位置，属于点标注。",
  },
  {
    id: 22,
    type: "single",
    question: "标注前准备工作不包括?",
    options: ["制定规范", "定义标签", "直接开始标注", "数据清洗"],
    answer: "C",
    explanation: "直接开始标注不是准备工作，应该在准备工作完成后进行。",
  },
  {
    id: 23,
    type: "single",
    question: "标注质量控制不包括?",
    options: ["复核抽检", "规范标签", "随意修改标签", "修正错误"],
    answer: "C",
    explanation: "随意修改标签会破坏数据一致性，不属于质量控制措施。",
  },
  {
    id: 24,
    type: "single",
    question: "文本情感分类标注属于?",
    options: ["图像标注", "文本标注", "音频标注", "视频标注"],
    answer: "B",
    explanation: "文本情感分类是文本标注的一种类型。",
  },
  {
    id: 25,
    type: "single",
    question: "撤销标注操作常用快捷键是?",
    options: ["Ctrl+S", "Ctrl+Z", "Ctrl+C", "Ctrl+V"],
    answer: "B",
    explanation: "Ctrl+Z是常用的撤销操作快捷键。",
  },
  {
    id: 26,
    type: "single",
    question: "重复标注的正确处理方式是?",
    options: ["全部保留", "删除重复，保留正确一个", "全部删除", "忽略不管"],
    answer: "B",
    explanation: "遇到重复标注时，应删除重复项，只保留一个正确的标注。",
  },
  {
    id: 27,
    type: "single",
    question: "下列哪项不是标注常见错误?",
    options: ["标签错误", "框选不准", "图像清晰", "漏标目标"],
    answer: "C",
    explanation: "图像清晰是图片本身的属性，不属于标注错误。",
  },
  {
    id: 28,
    type: "single",
    question: "关系抽取标注主要标注什么?",
    options: ["实体间关系", "图像目标", "音频时间点", "视频帧数"],
    answer: "A",
    explanation: "关系抽取标注主要标注文本中实体之间的关系。",
  },
  {
    id: 29,
    type: "single",
    question: "检查标注文件时不关注?",
    options: ["标签规范性", "格式正确性", "图片美观度", "是否空标注"],
    answer: "C",
    explanation: "标注检查主要关注标注质量，不关注图片本身的美观度。",
  },
  {
    id: 30,
    type: "single",
    question: "1 and 0 = ?",
    options: ["True", "False", "1", "0"],
    answer: "D",
    explanation: "在逻辑运算中，1 and 0 的结果是0（False）。",
  },
  {
    id: 31,
    type: "single",
    question: "True and False = ?",
    options: ["True", "False", "0", "1"],
    answer: "B",
    explanation: "True and False 的逻辑与运算结果是False。",
  },
  {
    id: 32,
    type: "single",
    question: "4 + 5 * 3 = ?",
    options: ["19", "17", "129", "27"],
    answer: "A",
    explanation: "按照运算优先级，先乘除后加减：5 * 3=15，4+15=19。",
  },
  {
    id: 33,
    type: "single",
    question: "153 // 10 % 10 = ?",
    options: ["1", "5", "3", "53"],
    answer: "B",
    explanation: "153//10=15，15%10=5。",
  },
  {
    id: 34,
    type: "single",
    question: "random.randint(0, 1)可能产生的随机数是?",
    options: ["0", "2", "3", "4"],
    answer: "A",
    explanation: "random.randint(0, 1)可能产生0或1，选项A是可能值。",
  },
  {
    id: 35,
    type: "single",
    question: "借助于模块( )可以查看 Python语言的关键字。",
    options: ["randint", "random", "turtle", "keyword"],
    answer: "D",
    explanation: "Python的keyword模块可以查看所有关键字。",
  },
  {
    id: 36,
    type: "single",
    question: "在 Python语言中,变量名能够使用的字符一共有( )个。",
    options: ["62", "63", "53", "52"],
    answer: "B",
    explanation:
      "Python变量名可以使用52个英文字母（大小写）+10个数字+下划线，共63个字符。",
  },
  {
    id: 37,
    type: "single",
    question: "5.0的数据类型是?",
    options: ["float", "list", "str", "int"],
    answer: "A",
    explanation: "5.0是浮点数，数据类型为float。",
  },
  {
    id: 38,
    type: "single",
    question: "5 / 2 = ?",
    options: ["2.5", "3.0", "2.0", "3"],
    answer: "A",
    explanation: "在Python 3中，5/2的结果是2.5（浮点数除法）。",
  },
  {
    id: 39,
    type: "single",
    question: "( )是赋值运算符。",
    options: ["+=", "=", "!=", "=="],
    answer: "B",
    explanation: "= 是基本的赋值运算符。",
  },
  {
    id: 40,
    type: "single",
    question: "计算机中数据的编码方式包括原码、反码和( )三种。",
    options: ["明文", "密码", "补码", "加密"],
    answer: "C",
    explanation: "计算机中数据编码包括原码、反码和补码。",
  },
  {
    id: 41,
    type: "single",
    question: "人工智能(AI)的英文全称正确的是?",
    options: [
      "Artificial Information",
      "Artificial Intelligence",
      "Automatic Intelligence",
      "Automatic Information",
    ],
    answer: "B",
    explanation: "人工智能的英文全称是Artificial Intelligence。",
  },
  {
    id: 42,
    type: "single",
    question: "'人工智能'概念首次被提出是在( )年的达特茅斯会议上。",
    options: ["1946", "1956", "1965", "1966"],
    answer: "B",
    explanation: "人工智能概念在1956年的达特茅斯会议上首次被正式提出。",
  },
  {
    id: 43,
    type: "single",
    question: "ChatGPT由 OpenAI推出的时间是?",
    options: [
      "2022年11月30日",
      "2021年11月30日",
      "2022年12月30日",
      "2024年11月30日",
    ],
    answer: "A",
    explanation: "ChatGPT于2022年11月30日由OpenAI推出。",
  },
  {
    id: 44,
    type: "single",
    question: "人工智能训练师包含的工种数量是?",
    options: ["一个", "两个", "三个", "四个"],
    answer: "B",
    explanation: "人工智能训练师包含数据标注员和算法工程师两个工种。",
  },
  {
    id: 45,
    type: "single",
    question: "以下属于人工智能训练师工种的是?",
    options: ["数据标注员", "提示词工程师", "数据分析师", "以上都不是"],
    answer: "A",
    explanation: "数据标注员是人工智能训练师的工种之一。",
  },
  {
    id: 46,
    type: "single",
    question: "下面不属于大数据的5V特征的是?",
    options: ["Volume", "Variety", "Velocity", "Vary"],
    answer: "D",
    explanation:
      "大数据的5V特征包括Volume、Variety、Velocity、Value、Veracity，不包括Vary。",
  },
  {
    id: 47,
    type: "single",
    question: "大数据5V特征里，Volume对应的含义是?",
    options: ["多样", "高速", "真实性", "价值"],
    answer: "A",
    explanation: "文档中显示Volume对应'多样'，但实际Volume通常指'大量'。",
  },
  {
    id: 48,
    type: "single",
    question: "在人工智能三大分类中，目前人工智能的发展程度是?",
    options: ["弱人工智能", "强人工智能", "超人工智能", "以上都是"],
    answer: "A",
    explanation: "目前人工智能的发展程度是弱人工智能阶段。",
  },
  {
    id: 49,
    type: "single",
    question: "图灵测试初步判定机器具备智能的通过率阈值是?",
    options: ["20%", "30%", "40%", "50%"],
    answer: "B",
    explanation: "图灵测试初步判定机器具备智能的通过率阈值是30%。",
  },
  {
    id: 50,
    type: "single",
    question: "被誉为'计算机科学之父'和'人工智能理论的奠基人'的是?",
    options: ["冯·诺依曼", "艾伦·图灵", "克劳德·香农", "马文·明斯基"],
    answer: "B",
    explanation: "艾伦·图灵被誉为'计算机科学之父'和'人工智能理论的奠基人'。",
  },
  {
    id: 51,
    type: "single",
    question: "人类九大智能中，擅长运用双手改造事物的能力属于?",
    options: ["语言智能", "身体运动智能", "空间智能", "自然智能"],
    answer: "B",
    explanation: "运用双手改造事物的能力属于身体运动智能。",
  },
  {
    id: 52,
    type: "single",
    question: "人工智能系统完成各类任务的基础是大量的?",
    options: ["算法", "算力", "数据", "模型"],
    answer: "C",
    explanation: "数据是人工智能系统完成任务的基础。",
  },
  {
    id: 53,
    type: "single",
    question: "决定人工智能训练速度、模型复杂度的核心基石是?",
    options: ["数据量", "计算能力", "算法优化", "模型架构"],
    answer: "B",
    explanation: "计算能力是决定训练速度和模型复杂度的核心因素。",
  },
  {
    id: 54,
    type: "single",
    question: "机器学习中，需要标注好的数据集指导学习的是?",
    options: ["监督学习", "无监督学习", "强化学习", "半监督学习"],
    answer: "A",
    explanation: "监督学习需要标注好的数据集进行学习指导。",
  },
  {
    id: 55,
    type: "single",
    question: "模拟人类注意力功能，让模型关注输入数据核心部分的是?",
    options: ["Transformer架构", "注意力机制", "优化算法", "损失函数"],
    answer: "B",
    explanation: "注意力机制模拟人类注意力，让模型关注输入数据的核心部分。",
  },
  {
    id: 56,
    type: "single",
    question: "大模型核心技术围绕的架构是?",
    options: ["CNN", "RNN", "Transformer", "LSTM"],
    answer: "C",
    explanation: "大模型核心技术围绕Transformer架构。",
  },
  {
    id: 57,
    type: "single",
    question: "监督学习中，预测房价这类连续数值的任务称为?",
    options: ["分类", "回归", "聚类", "降维"],
    answer: "B",
    explanation: "预测连续数值的任务称为回归。",
  },
  {
    id: 58,
    type: "single",
    question: "监督学习中，区分猫狗这类离散类别的任务是?",
    options: ["分类", "回归", "聚类", "关联分析"],
    answer: "A",
    explanation: "区分离散类别的任务称为分类。",
  },
  {
    id: 59,
    type: "single",
    question: "强化学习中，智能体从环境中获得的反馈的方式是?",
    options: ["动作", "状态", "奖励", "策略"],
    answer: "C",
    explanation: "智能体从环境中获得奖励作为反馈。",
  },
  {
    id: 60,
    type: "single",
    question: "衡量模型预测结果与真实结果偏差的函数是?",
    options: ["激活函数", "损失函数", "归一化函数", "聚合函数"],
    answer: "B",
    explanation: "损失函数用于衡量预测结果与真实结果的偏差。",
  },
  {
    id: 61,
    type: "single",
    question: "模型训练阶段需在( )上达到理想评估指标。",
    options: ["训练集", "验证集", "测试集", "新的数据"],
    answer: "D",
    explanation: "模型最终需要在新的数据上达到理想评估指标。",
  },
  {
    id: 62,
    type: "single",
    question: "模型测试阶段验证模型效果的数据集是?",
    options: ["训练集", "验证集", "测试集", "标注集"],
    answer: "C",
    explanation: "测试集用于验证模型最终效果。",
  },
  {
    id: 63,
    type: "single",
    question: "混淆矩阵中，TP的含义是?",
    options: ["真正类", "假正类", "真负类", "假负类"],
    answer: "A",
    explanation: "TP表示真正类（True Positive）。",
  },
  {
    id: 64,
    type: "single",
    question: "特征工程的核心是将原始数据转化为?",
    options: ["文本数据", "结构化数值特征", "图像数据", "语音数据"],
    answer: "B",
    explanation: "特征工程将原始数据转化为结构化数值特征。",
  },
  {
    id: 65,
    type: "single",
    question: "数据清洗的核心目的是?",
    options: ["增加数据量", "取得高质量数据", "加快数据处理速度", "加密数据"],
    answer: "B",
    explanation: "数据清洗的核心目的是获得高质量数据。",
  },
  {
    id: 66,
    type: "single",
    question: "下列关于人工智能的说法正确的是?",
    options: [
      "是自动化的生产线",
      "是在计算机上实现人类智能的技术科学",
      "是单一的复杂程序",
      "仅属于伦理道德问题",
    ],
    answer: "B",
    explanation: "人工智能是在计算机上实现人类智能的技术科学。",
  },
  {
    id: 67,
    type: "single",
    question: "深度学习是哪个领域的新研究方向?",
    options: ["图像处理", "专家系统", "机器学习", "数据挖掘"],
    answer: "C",
    explanation: "深度学习是机器学习领域的新研究方向。",
  },
  {
    id: 68,
    type: "single",
    question: "人工智能诞生于20世纪的?",
    options: ["40~50年代", "50~70年代", "70~80年代", "80~90年代"],
    answer: "A",
    explanation: "人工智能诞生于20世纪40~50年代。",
  },
  {
    id: 69,
    type: "single",
    question: "以下不属于大数据5V特征的是?",
    options: ["Volume", "Valley", "Velocity", "Veracity"],
    answer: "B",
    explanation: "Valley不属于大数据的5V特征。",
  },
  {
    id: 70,
    type: "single",
    question: "AlphaGo战胜李世石主要依赖的技术是?",
    options: ["专家系统", "强化学习", "知识图谱", "机器视觉"],
    answer: "B",
    explanation: "AlphaGo主要依赖强化学习技术。",
  },
  {
    id: 71,
    type: "single",
    question: "下列属于无监督学习的任务是?",
    options: ["分类", "聚类", "回归", "预测"],
    answer: "B",
    explanation: "聚类是无监督学习的典型任务。",
  },
  {
    id: 72,
    type: "single",
    question: "图灵测试的核心目的是?",
    options: [
      "测试计算机计算速度",
      "判断机器是否具有智能",
      "评估硬件性能",
      "检测算法效率",
    ],
    answer: "B",
    explanation: "图灵测试的核心目的是判断机器是否具有智能。",
  },
  {
    id: 73,
    type: "single",
    question: "以下属于'脏数据'特点的是?",
    options: ["精准规范", "准确无误", "陈旧过时", "格式统一"],
    answer: "C",
    explanation: "陈旧过时是脏数据的特点之一。",
  },
  {
    id: 74,
    type: "single",
    question: "数据整理的目的不包括?",
    options: ["系统化", "条理化", "科学化", "人性化"],
    answer: "D",
    explanation: "数据整理的目的不包括人性化。",
  },
  {
    id: 75,
    type: "single",
    question: "常见的数据汇总方法不包括?",
    options: ["基本统计汇总", "分组汇总", "条件汇总", "随机汇总"],
    answer: "D",
    explanation: "随机汇总不是常见的数据汇总方法。",
  },
  {
    id: 76,
    type: "single",
    question: "下列不属于聚合函数的是?",
    options: ["max", "sum", "min", "group"],
    answer: "D",
    explanation: "group不是聚合函数，而是分组操作。",
  },
  {
    id: 77,
    type: "single",
    question: "常用的去重方法不包括?",
    options: ["哈希算法", "特征向量", "深度学习", "排序算法"],
    answer: "C",
    explanation: "深度学习不常用于数据去重操作。",
  },
  {
    id: 78,
    type: "single",
    question: "图像特征统计方法中不包括?",
    options: ["均值", "方差", "边缘检测", "灰度共生矩阵"],
    answer: "C",
    explanation: "边缘检测是特征提取方法，不是特征统计方法。",
  },
  {
    id: 79,
    type: "single",
    question: "文本数据整理的操作不包括?",
    options: ["去除重复文本", "处理缺失值", "文本翻译", "文本归一化"],
    answer: "C",
    explanation: "文本翻译不属于文本数据整理的基本操作。",
  },
  {
    id: 80,
    type: "single",
    question: "智能系统的功能分类不包括?",
    options: ["感知功能", "认知功能", "执行功能", "存储功能"],
    answer: "D",
    explanation: "存储功能不是智能系统的核心功能分类。",
  },
  {
    id: 81,
    type: "judge",
    question: "Praat支持脚本编写和批处理，可提高音频标注效率。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "Praat确实支持脚本编写和批处理功能，可以提高音频标注效率。",
  },
  {
    id: 82,
    type: "judge",
    question: "LabelMe仅支持矩形框标注，不支持点和线。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "LabelMe支持矩形框、多边形、点和线等多种标注工具。",
  },
  {
    id: 83,
    type: "judge",
    question: "CSV是图像标注的主流导出格式。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "图像标注的主流导出格式包括JSON、XML等，CSV不常用。",
  },
  {
    id: 84,
    type: "judge",
    question: "Doccano可用于文本实体、分类、关系标注。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "Doccano支持文本实体标注、分类标注和关系标注。",
  },
  {
    id: 85,
    type: "judge",
    question: "直方图均衡化属于图像重采样方法。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "直方图均衡化是图像增强方法，不属于图像重采样方法。",
  },
  {
    id: 86,
    type: "judge",
    question: "True or False的运算结果是False。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "True or False的运算结果是True。",
  },
  {
    id: 87,
    type: "judge",
    question: "十六进制数的引导符是0x(不区分x的大小写)。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "十六进制数的引导符是0x，x不区分大小写。",
  },
  {
    id: 88,
    type: "judge",
    question: "len('='*5)的值等于5。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "'='*5的结果是'====='，长度为5。",
  },
  {
    id: 89,
    type: "judge",
    question: "Python语言自带的集成开发工具IDLE有两种使用方式。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "IDLE有交互模式和脚本模式两种使用方式。",
  },
  {
    id: 90,
    type: "judge",
    question: "__init__()是类的一个特殊方法。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "__init__()是Python类的构造函数，是一个特殊方法。",
  },
  {
    id: 91,
    type: "judge",
    question: "在达特茅斯会议正式提出了人工智能概念。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "人工智能概念在1956年的达特茅斯会议上正式提出。",
  },
  {
    id: 92,
    type: "judge",
    question: "强人工智能目前已经实现大规模商用。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "强人工智能目前尚未实现大规模商用。",
  },
  {
    id: 93,
    type: "judge",
    question:
      "人类九大智能中，存在智能是指思考关于生命、死亡、存在、宇宙等终极问题的能力。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "存在智能确实指思考生命、死亡、宇宙等终极问题的能力。",
  },
  {
    id: 94,
    type: "judge",
    question: "自注意力机制是Transformer架构的核心组成部分。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "自注意力机制是Transformer架构的核心技术。",
  },
  {
    id: 95,
    type: "judge",
    question: "损失函数值越大，说明模型的拟合效果越好。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "损失函数值越小，说明模型的拟合效果越好。",
  },
  {
    id: 96,
    type: "judge",
    question: "数据清洗可以去除数据中的缺失值、重复值和异常值。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "数据清洗的主要目标就是处理缺失值、重复值和异常值。",
  },
  {
    id: 97,
    type: "judge",
    question: "聚类是监督学习的典型任务。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "聚类是无监督学习的典型任务。",
  },
  {
    id: 98,
    type: "judge",
    question: "聚合函数的作用是将多行数据计算后返回一个标量值。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "聚合函数确实将多行数据计算后返回一个标量值。",
  },
  {
    id: 99,
    type: "judge",
    question: "智能系统的感知能力包括视觉、听觉等感官模拟。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "智能系统的感知能力包括视觉、听觉等感官模拟功能。",
  },
  {
    id: 100,
    type: "judge",
    question: "特征工程是连接原始数据和机器学习模型的关键步骤。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "特征工程确实是连接原始数据和机器学习模型的关键步骤。",
  },
  {
    id: 101,
    type: "single",
    question: "下列哪项属于数据增强而非重采样?",
    options: ["双线性插值", "旋转图像", "最近邻插值", "缩放尺寸"],
    answer: "B",
    explanation: "旋转图像是数据增强方法，而其他选项属于图像重采样方法。",
  },
  {
    id: 102,
    type: "single",
    question: "数据标注中'标签'指的是?",
    options: ["目标类别", "文件名称", "标注时间", "图片路径"],
    answer: "A",
    explanation: "在数据标注中，'标签'指的是目标类别或分类标签。",
  },
  {
    id: 103,
    type: "single",
    question: "COCO数据集标注格式为?",
    options: ["XML", "JSON", "TXT", "CSV"],
    answer: "B",
    explanation: "COCO数据集使用JSON格式存储标注信息。",
  },
  {
    id: 104,
    type: "single",
    question: "音频标注工具是?",
    options: ["LabelImg", "Praat", "Doccano", "LabelMe"],
    answer: "B",
    explanation: "Praat是专业的音频标注和分析工具。",
  },
  {
    id: 105,
    type: "single",
    question: "图像尺寸调整对应的技术是?",
    options: ["重采样", "灰度化", "二值化", "滤波"],
    answer: "A",
    explanation: "图像尺寸调整通常通过重采样技术实现。",
  },
  {
    id: 106,
    type: "single",
    question: "数据拆分时一般不依赖?",
    options: ["规则", "可视化工具", "随机划分", "随意拆分"],
    answer: "D",
    explanation: "数据拆分应该有依据，不应该是随意拆分。",
  },
  {
    id: 107,
    type: "single",
    question: "下列哪种工具主要用于图像标注?",
    options: ["Doccano", "LabelImg", "Praat", "记事本"],
    answer: "B",
    explanation: "LabelImg是专门用于图像标注的工具。",
  },
  {
    id: 108,
    type: "single",
    question: "图像标注中，用于标注不规则目标的工具是?",
    options: ["矩形框", "多边形", "单点", "直线"],
    answer: "B",
    explanation: "多边形工具适合标注不规则形状的目标。",
  },
  {
    id: 109,
    type: "single",
    question: "下列哪种格式是LabelImg支持导出的?",
    options: ["CSV", "Pascal VOC XML", "Excel", "PDF"],
    answer: "B",
    explanation: "LabelImg支持导出Pascal VOC XML格式。",
  },
  {
    id: 110,
    type: "single",
    question: "文本标注中，实体标注的核心是标注什么?",
    options: [
      "句子情感",
      "文本意图",
      "特定类型的词语(人名、地名等)",
      "文本长度",
    ],
    answer: "C",
    explanation:
      "实体标注的核心是标注特定类型的词语，如人名、地名、组织机构名等。",
  },
  {
    id: 111,
    type: "single",
    question: "下列哪项属于音频标注的核心内容?",
    options: ["目标坐标", "语音片段的起止时间", "文本类别", "图像掩码"],
    answer: "B",
    explanation: "音频标注的核心内容是标注语音片段的起止时间。",
  },
  {
    id: 112,
    type: "single",
    question: "数据清洗中，处理空标注的正确方式是?",
    options: ["保留空标注", "删除空标注或补充标注", "忽略不管", "替换为空文件"],
    answer: "B",
    explanation: "处理空标注的正确方式是删除或补充标注，不能保留或忽略。",
  },
  {
    id: 113,
    type: "single",
    question: "下列哪种不属于数据标注的类型?",
    options: ["图像标注", "文本标注", "数据建模", "音频标注"],
    answer: "C",
    explanation: "数据建模不属于数据标注类型，它是数据科学的一个阶段。",
  },
  {
    id: 114,
    type: "single",
    question: "LabelMe中，绘制多边形标注时，结束绘制的操作是?",
    options: ["按回车", "按空格", "双击最后一个点", "点击删除按钮"],
    answer: "C",
    explanation: "在LabelMe中绘制多边形时，双击最后一个点结束绘制。",
  },
  {
    id: 115,
    type: "single",
    question: "下列哪种算法不属于图像重采样?",
    options: ["双立方插值", "最近邻插值", "中值滤波", "双线性插值"],
    answer: "C",
    explanation: "中值滤波是图像去噪方法，不属于重采样算法。",
  },
  {
    id: 116,
    type: "single",
    question: "数据标注中，'漏标'属于哪种质量问题?",
    options: ["格式错误", "标注不完整", "标签错误", "重复标注"],
    answer: "B",
    explanation: "'漏标'属于标注不完整问题。",
  },
  {
    id: 117,
    type: "single",
    question: "Doccano中，创建标签时不需要设置的是?",
    options: ["标签名称", "标签颜色", "标签对应的实体类型", "标注员姓名"],
    answer: "D",
    explanation: "创建标签时不需要设置标注员姓名。",
  },
  {
    id: 118,
    type: "single",
    question: "下列哪种工具不能用于音频标注?",
    options: ["Praat", "LabelMe", "Audacity", "LabelStudio"],
    answer: "B",
    explanation: "LabelMe是图像标注工具，不能用于音频标注。",
  },
  {
    id: 119,
    type: "single",
    question: "目标检测标注中，标注框的核心要求是?",
    options: [
      "框选范围越大越好",
      "精准框选目标，不超出也不遗漏",
      "框选范围越小越好",
      "随意框选即可",
    ],
    answer: "B",
    explanation: "目标检测标注要求精准框选目标，既不超出也不遗漏。",
  },
  {
    id: 120,
    type: "single",
    question: "下列哪种格式常用于存储文本标注的实体信息?",
    options: ["PNG", "JSON", "JPG", "BMP"],
    answer: "B",
    explanation: "JSON格式常用于存储文本标注的实体信息。",
  },
  {
    id: 121,
    type: "single",
    question: "数据增强的目的是?",
    options: [
      "减少数据量",
      "提升标注速度",
      "丰富数据多样性，提升模型泛化能力",
      "简化标注流程",
    ],
    answer: "C",
    explanation: "数据增强的目的是丰富数据多样性，提升模型泛化能力。",
  },
  {
    id: 122,
    type: "single",
    question: "标注规范的核心作用是?",
    options: [
      "提高标注速度",
      "保证标注数据的一致性和准确性",
      "增加标签数量",
      "简化工具操作",
    ],
    answer: "B",
    explanation: "标注规范的核心作用是保证标注数据的一致性和准确性。",
  },
  {
    id: 123,
    type: "single",
    question: "下列哪项属于文本意图识别标注?",
    options: [
      "标注句子中的人名",
      "标注句子是'查询'还是'购买'意图",
      "标注图像中的目标",
      "标注音频的时间点",
    ],
    answer: "B",
    explanation: "文本意图识别标注是识别句子的意图，如查询、购买等。",
  },
  {
    id: 124,
    type: "single",
    question: "LabelImg中，默认的标注文件保存路径是?",
    options: ["系统桌面", "与图像文件同一目录", "我的文档", "C盘根目录"],
    answer: "B",
    explanation: "LabelImg默认将标注文件保存在与图像文件同一目录。",
  },
  {
    id: 125,
    type: "single",
    question: "下列哪项不是数据清洗的常见操作?",
    options: ["删除重复标注", "修正标签错误", "增加数据量", "处理空标注"],
    answer: "C",
    explanation: "增加数据量不是数据清洗操作，是数据增强操作。",
  },
  {
    id: 126,
    type: "single",
    question: "音频标注中，标注'语音转文字'对应的内容属于?",
    options: ["时间点标注", "转写标注", "情感标注", "意图标注"],
    answer: "B",
    explanation: "语音转文字对应的是转写标注。",
  },
  {
    id: 127,
    type: "single",
    question: "下列哪种标注方式适用于车道线标注?",
    options: ["矩形框", "多边形", "折线", "单点"],
    answer: "C",
    explanation: "车道线标注通常使用折线标注方式。",
  },
  {
    id: 128,
    type: "single",
    question: "Doccano支持的标注任务不包括?",
    options: ["文本分类", "实体标注", "图像分割", "关系标注"],
    answer: "C",
    explanation: "Doccano是文本标注工具，不支持图像分割任务。",
  },
  {
    id: 129,
    type: "single",
    question: "数据标注中，IOU的取值范围是?",
    options: ["0-1", "1-10", "0-100", "无固定范围"],
    answer: "A",
    explanation: "IOU（交并比）的取值范围是0到1。",
  },
  {
    id: 130,
    type: "single",
    question: "下列哪种工具支持批量标注操作?",
    options: ["记事本", "LabelMe", "画图工具", "计算器"],
    answer: "B",
    explanation: "LabelMe支持批量标注操作。",
  },
  {
    id: 131,
    type: "single",
    question: "图像标注中，'掩码标注'主要用于哪种任务?",
    options: ["目标检测", "语义分割", "关键点检测", "图像分类"],
    answer: "B",
    explanation: "掩码标注主要用于语义分割任务。",
  },
  {
    id: 132,
    type: "single",
    question: "文本标注中，情感细粒度标注不包括?",
    options: ["积极", "消极", "中性", "模糊"],
    answer: "D",
    explanation: "情感细粒度标注通常包括积极、消极、中性，不包括模糊。",
  },
  {
    id: 133,
    type: "single",
    question: "下列哪项属于数据标注后的处理步骤?",
    options: ["制定标注规范", "导出标注结果", "定义标签", "数据清洗"],
    answer: "B",
    explanation: "导出标注结果是标注完成后的处理步骤。",
  },
  {
    id: 134,
    type: "single",
    question: "LabelMe中，修改标注形状的操作是?",
    options: [
      "直接点击形状拖动",
      "选中形状后拖动控制点",
      "重新绘制形状",
      "无法修改",
    ],
    answer: "B",
    explanation:
      "在LabelMe中修改标注形状，需要先选中形状，然后拖动控制点进行调整。",
  },
  {
    id: 135,
    type: "single",
    question: "下列哪种格式不是常见的标注结果格式?",
    options: ["XML", "JSON", "TXT", "MP4"],
    answer: "D",
    explanation: "MP4是视频格式，不是常见的标注结果格式。",
  },
  {
    id: 136,
    type: "single",
    question: "数据标注质量抽检的目的是?",
    options: [
      "统计标注数量",
      "检查标注准确性，及时修正错误",
      "提高标注速度",
      "增加标签数量",
    ],
    answer: "B",
    explanation: "质量抽检的目的是检查标注准确性，及时发现和修正错误。",
  },
  {
    id: 137,
    type: "single",
    question: "音频标注中，'静音段标注'的核心是标注?",
    options: ["语音内容", "静音的起止时间", "语音情感", "语音意图"],
    answer: "B",
    explanation: "静音段标注的核心是标注静音的起止时间。",
  },
  {
    id: 138,
    type: "single",
    question: "下列哪项不属于图像标注的工具?",
    options: ["LabelImg", "LabelMe", "Doccano", "LabelStudio"],
    answer: "C",
    explanation: "Doccano是文本标注工具，不属于图像标注工具。",
  },
  {
    id: 139,
    type: "single",
    question: "数据拆分中，基于规则拆分的核心是?",
    options: [
      "随机划分",
      "按照预设条件(如类别、时间)划分",
      "按数据量平均划分",
      "随意划分",
    ],
    answer: "B",
    explanation: "基于规则拆分是按照预设条件（如类别、时间等）进行划分。",
  },
  {
    id: 140,
    type: "single",
    question: "标注文件中，坐标值的作用是?",
    options: [
      "标记文件大小",
      "标记目标在图像中的位置",
      "标记标注时间",
      "标记标签数量",
    ],
    answer: "B",
    explanation: "坐标值用于标记目标在图像中的位置。",
  },
  {
    id: 141,
    type: "single",
    question: "首次提出'人工智能'概念的会议是?",
    options: ["巴黎会议", "达特茅斯会议", "日内瓦会议", "华盛顿会议"],
    answer: "B",
    explanation: "人工智能概念在1956年的达特茅斯会议上首次被正式提出。",
  },
  {
    id: 142,
    type: "single",
    question: "OpenAI推出的ChatGPT是哪类人工智能产品?",
    options: ["图像识别机器人", "对话聊天机器人", "工业机器人", "服务机器人"],
    answer: "B",
    explanation: "ChatGPT是OpenAI推出的对话聊天机器人。",
  },
  {
    id: 143,
    type: "single",
    question: "数据标注员属于以下哪个职业的工种?",
    options: ["数据分析师", "人工智能训练师", "算法工程师", "软件测试工程师"],
    answer: "B",
    explanation: "数据标注员是人工智能训练师的工种之一。",
  },
  {
    id: 144,
    type: "single",
    question: "大数据5V特征中，Variety对应的中文含义是?",
    options: ["大量", "高速", "多样", "价值"],
    answer: "C",
    explanation: "Variety在大数据5V特征中对应'多样'。",
  },
  {
    id: 145,
    type: "single",
    question: "人工智能中，具备与人类同等智能水平的是?",
    options: ["弱人工智能", "强人工智能", "超人工智能", "通用人工智能"],
    answer: "B",
    explanation: "强人工智能指具备与人类同等智能水平的人工智能。",
  },
  {
    id: 146,
    type: "single",
    question: "图灵测试的提出者是英国的?",
    options: ["艾伦·图灵", "艾伦·纽厄尔", "约翰·纳什", "亚瑟·塞缪尔"],
    answer: "A",
    explanation: "图灵测试由英国数学家、计算机科学家艾伦·图灵提出。",
  },
  {
    id: 147,
    type: "single",
    question: "人类九大智能中，能有效运用书面文字的能力属于?",
    options: ["逻辑数学智能", "语言智能", "内省智能", "人际交往智能"],
    answer: "B",
    explanation: "有效运用书面文字的能力属于语言智能。",
  },
  {
    id: 148,
    type: "single",
    question: "图像识别、语音识别等AI任务的核心学习基础是?",
    options: ["硬件", "算法", "数据", "算力"],
    answer: "C",
    explanation: "数据是AI任务的核心学习基础。",
  },
  {
    id: 149,
    type: "single",
    question: "算力对人工智能的影响不包括?",
    options: ["训练速度", "模型复杂度", "应用能力", "数据量"],
    answer: "D",
    explanation: "算力不影响数据量，数据量是独立于算力的因素。",
  },
  {
    id: 150,
    type: "single",
    question: "机器学习中，部分数据标注、部分数据未标注的学习方式是?",
    options: ["监督学习", "半监督学习", "无监督学习", "强化学习"],
    answer: "B",
    explanation: "半监督学习使用部分标注数据和部分未标注数据进行学习。",
  },
  {
    id: 151,
    type: "single",
    question: "能实现长距离依赖建模的大模型核心技术是?",
    options: ["聚合操作", "自注意力机制", "卷积操作", "循环操作"],
    answer: "B",
    explanation: "自注意力机制能有效建模长距离依赖关系。",
  },
  {
    id: 152,
    type: "single",
    question: "监督学习中，分类任务的预测结果是?",
    options: ["连续数值", "离散类别", "模糊值", "概率值"],
    answer: "B",
    explanation: "分类任务的预测结果是离散的类别标签。",
  },
  {
    id: 153,
    type: "single",
    question: "强化学习中，智能体为了获得最优结果会尝试不同的?",
    options: ["奖励", "环境", "动作", "反馈"],
    answer: "C",
    explanation: "强化学习中，智能体会尝试不同的动作以获得最优结果。",
  },
  {
    id: 154,
    type: "single",
    question: "模型参数优化的重要依据是?",
    options: ["激活函数", "损失函数", "卷积函数", "池化函数"],
    answer: "B",
    explanation: "损失函数是模型参数优化的重要依据。",
  },
  {
    id: 155,
    type: "single",
    question: "模型训练过程中，用于调整参数的数据集是?",
    options: ["新数据", "训练集", "验证集", "测试集"],
    answer: "C",
    explanation: "验证集用于在训练过程中调整模型参数。",
  },
  {
    id: 156,
    type: "single",
    question: "最终验证模型泛化能力的数据集是?",
    options: ["训练集", "验证集", "测试集", "标注集"],
    answer: "C",
    explanation: "测试集用于最终验证模型的泛化能力。",
  },
  {
    id: 157,
    type: "single",
    question: "混淆矩阵中，代表'假正类'的是?",
    options: ["TP", "FP", "TN", "FN"],
    answer: "B",
    explanation: "FP（False Positive）代表假正类。",
  },
  {
    id: 158,
    type: "single",
    question: "从原始数据中提取、构造有效特征的过程是?",
    options: ["数据清洗", "特征工程", "数据汇总", "数据整理"],
    answer: "B",
    explanation: "特征工程是从原始数据中提取、构造有效特征的过程。",
  },
  {
    id: 159,
    type: "single",
    question: "去除数据中的错误、缺失值是以下哪项操作的内容?",
    options: ["数据标注", "数据清洗", "数据汇总", "特征工程"],
    answer: "B",
    explanation: "数据清洗包括去除数据中的错误和缺失值。",
  },
  {
    id: 160,
    type: "single",
    question: "人工智能的本质是在计算机上实现的?",
    options: ["自动化流程", "人类智能相关技术科学", "硬件设备", "软件程序"],
    answer: "B",
    explanation: "人工智能的本质是在计算机上实现的人类智能相关技术科学。",
  },
  {
    id: 161,
    type: "single",
    question: "让机器学习更接近人工智能最初目标的研究方向是?",
    options: ["深度学习", "传统机器学习", "专家系统", "知识图谱"],
    answer: "A",
    explanation: "深度学习让机器学习更接近人工智能的初衷。",
  },
  {
    id: 162,
    type: "single",
    question: "大数据5V特征中，Value代表的含义是?",
    options: ["真实性", "价值", "高速", "多样"],
    answer: "B",
    explanation: "Value在大数据5V特征中代表'价值'。",
  },
  {
    id: 163,
    type: "single",
    question: "以下属于强化学习典型应用的是?",
    options: ["人脸识别", "围棋程序AlphaGo", "文本分类", "数据聚类"],
    answer: "B",
    explanation: "围棋程序AlphaGo是强化学习的典型应用。",
  },
  {
    id: 164,
    type: "single",
    question: "无监督学习不需要的是?",
    options: ["原始数据", "标注好的标签", "算法模型", "计算资源"],
    answer: "B",
    explanation: "无监督学习不需要标注好的标签。",
  },
  {
    id: 165,
    type: "single",
    question: "图灵测试中，若机器通过率低于30%，则判定其?",
    options: ["具备智能", "初步具备智能", "不具备智能", "无法判断"],
    answer: "C",
    explanation: "图灵测试中，通过率低于30%判定为不具备智能。",
  },
  {
    id: 166,
    type: "single",
    question: "脏数据的特点不包括?",
    options: ["不准确", "不完整", "精准规范", "格式混乱"],
    answer: "C",
    explanation: "精准规范是高质量数据的特点，不是脏数据的特点。",
  },
  {
    id: 167,
    type: "single",
    question: "数据整理的核心是让原始资料变得?",
    options: ["人性化", "系统化、条理化", "数量更多", "格式不统一"],
    answer: "B",
    explanation: "数据整理的核心是让原始资料系统化、条理化。",
  },
  {
    id: 168,
    type: "single",
    question: "sum、mean属于哪种数据汇总方法?",
    options: ["基本统计汇总", "分组汇总", "条件汇总", "以上都不是"],
    answer: "A",
    explanation: "sum、mean属于基本统计汇总方法。",
  },
  {
    id: 169,
    type: "single",
    question: "groupby对应的是哪种数据汇总方法?",
    options: ["基本统计汇总", "分组汇总", "条件汇总", "随机汇总"],
    answer: "B",
    explanation: "groupby对应的是分组汇总方法。",
  },
  {
    id: 170,
    type: "single",
    question: "下列属于聚合函数的是?",
    options: ["group", "sort", "max", "filter"],
    answer: "C",
    explanation: "max是聚合函数，用于求最大值。",
  },
  {
    id: 171,
    type: "single",
    question: "哈希算法可用于数据处理中的?",
    options: ["去重", "标注", "汇总", "清洗"],
    answer: "A",
    explanation: "哈希算法常用于数据去重操作。",
  },
  {
    id: 172,
    type: "single",
    question: "灰度共生矩阵属于哪种特征统计方法?",
    options: ["文本特征", "图像特征", "语音特征", "视频特征"],
    answer: "B",
    explanation: "灰度共生矩阵是图像纹理特征统计方法。",
  },
  {
    id: 173,
    type: "single",
    question: "文本归一化是以下哪项操作的内容?",
    options: ["文本数据整理", "图像数据处理", "语音数据识别", "数据标注"],
    answer: "A",
    explanation: "文本归一化是文本数据整理的操作内容之一。",
  },
  {
    id: 174,
    type: "single",
    question: "智能系统感知环境的能力属于其?",
    options: ["认知功能", "执行功能", "感知功能", "存储功能"],
    answer: "C",
    explanation: "感知环境的能力属于智能系统的感知功能。",
  },
  {
    id: 175,
    type: "single",
    question: "记录智能系统功能应用情况的主要目的是?",
    options: ["提高系统稳定性", "提高系统颜值", "增加功能数量", "降低算力消耗"],
    answer: "A",
    explanation: "记录功能应用情况的主要目的是提高系统稳定性。",
  },
  {
    id: 176,
    type: "single",
    question: "下面属于人工智能训练师的工种的是?",
    options: ["提示词工程师", "人工智能算法测试员", "算法工程师", "数据分析师"],
    answer: "B",
    explanation: "人工智能算法测试员是人工智能训练师的工种之一。",
  },
  {
    id: 177,
    type: "single",
    question: "人类九大智能中，察觉他人情绪的能力属于?",
    options: ["人际交往智能", "内省智能", "自然智能", "存在智能"],
    answer: "A",
    explanation: "察觉他人情绪的能力属于人际交往智能。",
  },
  {
    id: 178,
    type: "single",
    question: "注意力机制的核心作用是让模型关注输入数据的?",
    options: ["所有部分", "不重要部分", "最重要部分", "随机部分"],
    answer: "C",
    explanation: "注意力机制让模型关注输入数据的最重要部分。",
  },
  {
    id: 179,
    type: "single",
    question: "机器学习的四大学习方式不包括?",
    options: ["监督学习", "半监督学习", "无监督学习", "自主学习"],
    answer: "D",
    explanation: "自主学习不属于机器学习的四大基本学习方式。",
  },
  {
    id: 180,
    type: "single",
    question: "智能系统的认知功能主要负责?",
    options: ["感知环境", "分析判断", "执行动作", "存储数据"],
    answer: "B",
    explanation: "认知功能主要负责分析判断。",
  },
  {
    id: 181,
    type: "judge",
    question: "数据管理必须重新编写代码才能完成。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation:
      "数据管理可以通过工具、脚本或现有软件完成，不一定需要重新编写代码。",
  },
  {
    id: 182,
    type: "judge",
    question: "数据标注质量会直接影响模型训练效果。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "数据标注质量直接影响模型的学习效果和最终性能。",
  },
  {
    id: 183,
    type: "judge",
    question: "LabelMe删除标注必须先选中形状。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "在LabelMe中删除标注确实需要先选中要删除的形状。",
  },
  {
    id: 184,
    type: "judge",
    question: "XML和JSON都是常见标注结果格式。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "XML和JSON都是常见的数据标注存储格式。",
  },
  {
    id: 185,
    type: "judge",
    question: "双线性插值属于图像重采样算法。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "双线性插值是常用的图像重采样算法。",
  },
  {
    id: 186,
    type: "judge",
    question: "文本标签集用于定义需要标注的类别。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "文本标签集确实用于定义需要标注的实体或类别。",
  },
  {
    id: 187,
    type: "judge",
    question: "遍历标注文件只为统计文件数量。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "遍历标注文件不仅为了统计数量，更重要的是检查内容和质量。",
  },
  {
    id: 188,
    type: "judge",
    question: "数据可视化工具可用于辅助标签拆分。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "数据可视化工具可以帮助理解和拆分标签。",
  },
  {
    id: 189,
    type: "judge",
    question: "标注完成后格式不需要与模型匹配。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "标注格式需要与模型输入格式匹配，否则无法用于训练。",
  },
  {
    id: 190,
    type: "judge",
    question: "批处理脚本可以提升音频标注处理效率。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "批处理脚本可以自动化处理多个音频文件，提高效率。",
  },
  {
    id: 191,
    type: "judge",
    question: "2022年11月30日是ChatGPT的推出时间，是人工智能发展的重要里程碑。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "ChatGPT于2022年11月30日正式推出，确实是AI发展的重要里程碑。",
  },
  {
    id: 192,
    type: "judge",
    question: "人工智能训练师包含数据标注员和算法工程师两个工种。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation:
      "人工智能训练师确实包含数据标注员和算法工程师（或算法测试员）两个工种。",
  },
  {
    id: 193,
    type: "judge",
    question: "超人工智能是指超越人类智能水平的人工智能。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "超人工智能指在所有领域都超越人类智能水平的人工智能。",
  },
  {
    id: 194,
    type: "judge",
    question: "算力是人工智能技术发展的基石之一。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "算力确实是人工智能技术发展的重要基石。",
  },
  {
    id: 195,
    type: "judge",
    question: "回归任务的预测结果是离散的类别标签。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "回归任务预测连续数值，分类任务预测离散类别。",
  },
  {
    id: 196,
    type: "judge",
    question: "数据清洗能提高数据的准确性和一致性。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "数据清洗的主要目的就是提高数据的准确性和一致性。",
  },
  {
    id: 197,
    type: "judge",
    question: "深度学习是独立于机器学习的全新领域。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "深度学习是机器学习的一个分支，不是独立的全新领域。",
  },
  {
    id: 198,
    type: "judge",
    question: "聚类不需要提前标注数据，属于无监督学习。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "聚类是无监督学习，不需要提前标注数据。",
  },
  {
    id: 199,
    type: "judge",
    question: "边缘检测是图像特征统计的常用方法。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "边缘检测是特征提取方法，不是特征统计方法。",
  },
  {
    id: 200,
    type: "judge",
    question: "智能系统的功能分类包括感知、认知和执行功能。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "智能系统的三大功能分类确实是感知、认知和执行功能。",
  },
  {
    id: 201,
    type: "single",
    question: "下列不属于LabelMe支持的标注形状是?",
    options: ["矩形框", "多边形", "3D模型", "点和线"],
    answer: "C",
    explanation: "LabelMe不支持3D模型标注，主要用于2D图像标注。",
  },
  {
    id: 202,
    type: "single",
    question: "LabelImg主要用于哪种数据标注?",
    options: ["文本", "图像目标检测", "音频", "视频"],
    answer: "B",
    explanation: "LabelImg是专门用于图像目标检测标注的工具。",
  },
  {
    id: 203,
    type: "single",
    question: "下列哪种格式是图像标注中'不常用'的导出格式?",
    options: ["XML", "JSON", "EXE", "TXT"],
    answer: "C",
    explanation: "EXE是可执行文件格式，不用于存储图像标注结果。",
  },
  {
    id: 204,
    type: "single",
    question: "Doccano主要面向哪种标注任务?",
    options: ["图像分割", "文本标注", "语音标注", "视频标注"],
    answer: "B",
    explanation: "Doccano是专门用于文本标注的工具。",
  },
  {
    id: 205,
    type: "single",
    question: "图像重采样的主要目的是?",
    options: ["改变图像尺寸", "提高亮度", "增加噪声", "图像锐化"],
    answer: "A",
    explanation: "图像重采样的主要目的是改变图像的尺寸或分辨率。",
  },
  {
    id: 206,
    type: "single",
    question: "下列属于重采样方法的是?",
    options: ["直方图均衡化", "中值滤波", "双线性插值", "边缘检测"],
    answer: "C",
    explanation: "双线性插值是图像重采样的常用方法。",
  },
  {
    id: 207,
    type: "single",
    question: "数据标注中遍历标注文件的主要目的不包括?",
    options: ["检查标签正确性", "提取标注信息", "随意修改文件名", "检查格式"],
    answer: "C",
    explanation: "遍历标注文件不应该随意修改文件名。",
  },
  {
    id: 208,
    type: "single",
    question: "数据组织管理中，一般不需要执行的是?",
    options: ["建立目录结构", "定义分类规则", "随意删除源代码", "整理数据"],
    answer: "C",
    explanation: "数据组织管理不需要随意删除源代码。",
  },
  {
    id: 209,
    type: "single",
    question: "下列不属于数据标签拆分方法的是?",
    options: [
      "按规则拆分",
      "机器学习辅助拆分",
      "直接格式化硬盘",
      "可视化辅助拆分",
    ],
    answer: "C",
    explanation: "直接格式化硬盘会丢失所有数据，不是合理的标签拆分方法。",
  },
  {
    id: 210,
    type: "single",
    question: "Praat主要用于处理哪种数据?",
    options: ["图像", "音频/语音", "文本", "数据库"],
    answer: "B",
    explanation: "Praat是专业的音频/语音处理工具。",
  },
  {
    id: 211,
    type: "single",
    question: "目标检测最常用的标注形式是?",
    options: ["多边形", "矩形框", "点标注", "曲线标注"],
    answer: "B",
    explanation: "目标检测最常用矩形框（bounding box）进行标注。",
  },
  {
    id: 212,
    type: "single",
    question: "语义分割通常使用哪种标注?",
    options: ["矩形框", "掩码/多边形", "单点", "文字"],
    answer: "B",
    explanation: "语义分割通常使用掩码或多边形进行精确标注。",
  },
  {
    id: 213,
    type: "single",
    question: "YOLO模型训练常用标注格式是?",
    options: ["XML", "TXT", "CSV", "DOC"],
    answer: "B",
    explanation: "YOLO模型通常使用TXT格式存储标注信息。",
  },
  {
    id: 214,
    type: "single",
    question: "Pascal VOC数据集标注文件格式是?",
    options: ["JSON", "XML", "PNG", "AVI"],
    answer: "B",
    explanation: "Pascal VOC数据集使用XML格式存储标注信息。",
  },
  {
    id: 215,
    type: "single",
    question: "COCO数据集标注文件格式是?",
    options: ["XML", "JSON", "WAV", "JPG"],
    answer: "B",
    explanation: "COCO数据集使用JSON格式存储标注信息。",
  },
  {
    id: 216,
    type: "single",
    question: "命名实体识别(NER)属于?",
    options: ["图像标注", "文本标注", "音频标注", "视频标注"],
    answer: "B",
    explanation: "命名实体识别是文本标注的重要任务。",
  },
  {
    id: 217,
    type: "single",
    question: "人脸关键点检测属于哪种标注?",
    options: ["点标注", "框标注", "分类标注", "音频标注"],
    answer: "A",
    explanation: "人脸关键点检测需要标注关键点位置，属于点标注。",
  },
  {
    id: 218,
    type: "single",
    question: "标注中IOU用于衡量?",
    options: ["标注框重合度", "标注速度", "文件大小", "图片清晰度"],
    answer: "A",
    explanation: "IOU（交并比）用于衡量两个标注框的重合程度。",
  },
  {
    id: 219,
    type: "single",
    question: "IOU的取值范围是?",
    options: ["0~1", "0~10", "-1~1", "1~100"],
    answer: "A",
    explanation: "IOU的取值范围是0到1，0表示无重叠，1表示完全重叠。",
  },
  {
    id: 220,
    type: "single",
    question: "下列不属于标注质量问题的是?",
    options: ["漏标", "错标", "图像清晰", "重复标注"],
    answer: "C",
    explanation: "图像清晰是图片质量指标，不是标注质量问题。",
  },
  {
    id: 221,
    type: "single",
    question: "遇到重复标注，正确做法是?",
    options: ["全部保留", "删除重复，保留正确项", "全部删除", "不处理"],
    answer: "B",
    explanation: "遇到重复标注，应该删除重复项，只保留一个正确的标注。",
  },
  {
    id: 222,
    type: "single",
    question: "空标注文件应该?",
    options: ["直接用于训练", "修正或删除", "重命名保存", "加密存储"],
    answer: "B",
    explanation: "空标注文件应该修正或删除，不能用于训练。",
  },
  {
    id: 223,
    type: "single",
    question: "标注前准备工作不包括?",
    options: ["制定规范", "定义标签", "直接开始标注", "数据清洗"],
    answer: "C",
    explanation: "直接开始标注不是准备工作，应该是准备工作完成后才进行。",
  },
  {
    id: 224,
    type: "single",
    question: "标注规范的作用是?",
    options: ["统一标注标准", "加快标注速度", "减少标签数量", "简化工具操作"],
    answer: "A",
    explanation: "标注规范的主要作用是统一标注标准，保证一致性。",
  },
  {
    id: 225,
    type: "single",
    question: "撤销上一步标注操作常用快捷键是?",
    options: ["Ctrl+S", "Ctrl+Z", "Ctrl+C", "Ctrl+V"],
    answer: "B",
    explanation: "Ctrl+Z是常用的撤销操作快捷键。",
  },
  {
    id: 226,
    type: "single",
    question: "在LabelMe中删除标注必须?",
    options: ["直接按Delete", "先选中形状再删除", "重启软件", "无法删除"],
    answer: "B",
    explanation: "在LabelMe中删除标注需要先选中形状，再删除。",
  },
  {
    id: 227,
    type: "single",
    question: "下列哪种工具可用于音频标注?",
    options: ["LabelImg", "Praat", "Doccano", "Office Word"],
    answer: "B",
    explanation: "Praat是专业的音频标注工具。",
  },
  {
    id: 228,
    type: "single",
    question: "文本情感分类标注属于?",
    options: ["图像标注", "文本标注", "音频标注", "视频标注"],
    answer: "B",
    explanation: "文本情感分类是文本标注的一种。",
  },
  {
    id: 229,
    type: "single",
    question: "文本意图识别标注的是?",
    options: ["坐标", "意图类别", "音频时长", "图像尺寸"],
    answer: "B",
    explanation: "文本意图识别标注的是句子的意图类别。",
  },
  {
    id: 230,
    type: "single",
    question: "关系抽取标注主要标注?",
    options: ["实体间关系", "像素坐标", "声音频率", "图像亮度"],
    answer: "A",
    explanation: "关系抽取标注主要标注文本中实体之间的关系。",
  },
  {
    id: 231,
    type: "single",
    question: "数据增强的目的是?",
    options: ["减少数据量", "丰富数据多样性", "破坏标注结构", "降低精度"],
    answer: "B",
    explanation: "数据增强的目的是丰富数据多样性，提高模型泛化能力。",
  },
  {
    id: 232,
    type: "single",
    question: "下列属于数据增强的是?",
    options: ["图像旋转", "双立方插值", "最近邻插值", "图像缩放"],
    answer: "A",
    explanation: "图像旋转是数据增强的常用方法。",
  },
  {
    id: 233,
    type: "single",
    question: "标注文件中的坐标用于表示?",
    options: ["目标位置", "文件大小", "标注时间", "标签颜色"],
    answer: "A",
    explanation: "标注文件中的坐标用于表示目标在图像中的位置。",
  },
  {
    id: 234,
    type: "single",
    question: "下列不属于标注工具功能的是?",
    options: ["画框", "编辑标签", "模型训练", "导出文件"],
    answer: "C",
    explanation: "模型训练不是标注工具的功能，是训练平台的功能。",
  },
  {
    id: 235,
    type: "single",
    question: "数据标注质量对模型效果的影响是?",
    options: ["几乎无影响", "决定性影响", "轻微影响", "反向影响"],
    answer: "B",
    explanation: "数据标注质量对模型效果有决定性影响，'垃圾进，垃圾出'。",
  },
  {
    id: 236,
    type: "single",
    question: "在Python语言中，变量名能够使用的字符一共有( )个。",
    options: ["62", "63", "53", "52"],
    answer: "B",
    explanation:
      "Python变量名可以使用52个英文字母（大小写）+10个数字+下划线，共63个字符。",
  },
  {
    id: 237,
    type: "single",
    question: "5.0的数据类型是?",
    options: ["float", "list", "str", "int"],
    answer: "A",
    explanation: "5.0是浮点数，数据类型为float。",
  },
  {
    id: 238,
    type: "single",
    question: "5/2 = ?",
    options: ["2.5", "3.0", "2.0", "3"],
    answer: "A",
    explanation: "在Python 3中，5/2的结果是2.5（浮点数除法）。",
  },
  {
    id: 239,
    type: "single",
    question: "( )是复合赋值运算符。",
    options: ["+=", ">=", "!=", "="],
    answer: "A",
    explanation: "+= 是复合赋值运算符（加赋值运算符）。",
  },
  {
    id: 240,
    type: "single",
    question: "计算机中数据的编码方式包括( )、反码和补码三种。",
    options: ["加密", "密文", "原码", "明文"],
    answer: "C",
    explanation: "计算机中数据编码包括原码、反码和补码。",
  },
  {
    id: 241,
    type: "single",
    question: "人工智能的英文缩写是?",
    options: ["AI", "IT", "BI", "CI"],
    answer: "A",
    explanation: "人工智能的英文缩写是AI（Artificial Intelligence）。",
  },
  {
    id: 242,
    type: "single",
    question: "达特茅斯会议召开的年份是?",
    options: ["1945", "1956", "1967", "1978"],
    answer: "B",
    explanation: "达特茅斯会议于1956年召开，标志着人工智能学科的诞生。",
  },
  {
    id: 243,
    type: "single",
    question: "ChatGPT的研发公司是?",
    options: ["谷歌", "微软", "OpenAI", "百度"],
    answer: "C",
    explanation: "ChatGPT由OpenAI公司研发。",
  },
  {
    id: 244,
    type: "single",
    question: "以下哪项是人工智能训练师的核心工种之一?",
    options: ["前端开发工程师", "数据标注员", "产品经理", "运维工程师"],
    answer: "B",
    explanation: "数据标注员是人工智能训练师的核心工种之一。",
  },
  {
    id: 245,
    type: "single",
    question: "大数据5V特征中，Velocity的中文含义是?",
    options: ["大量", "多样", "高速", "真实"],
    answer: "C",
    explanation: "Velocity在大数据5V特征中对应'高速'。",
  },
  {
    id: 246,
    type: "single",
    question: "目前人工智能发展所处的主要阶段是?",
    options: ["弱人工智能", "强人工智能", "超人工智能", "通用人工智能"],
    answer: "A",
    explanation: "目前人工智能发展处于弱人工智能阶段。",
  },
  {
    id: 247,
    type: "single",
    question: "图灵测试初步判定机器有智能的通过率要求是?",
    options: ["≥20%", "≥30%", "≥40%", "≥50%"],
    answer: "B",
    explanation: "图灵测试初步判定机器有智能的通过率要求是≥30%。",
  },
  {
    id: 248,
    type: "single",
    question: "'人工智能理论的奠基人'是?",
    options: ["艾伦·图灵", "冯·诺依曼", "图灵·艾伦", "乔布斯"],
    answer: "A",
    explanation: "艾伦·图灵被誉为'人工智能理论的奠基人'。",
  },
  {
    id: 249,
    type: "single",
    question: "人类九大智能中，善于推理、归纳的能力属于?",
    options: ["语言智能", "逻辑数学智能", "空间智能", "音乐智能"],
    answer: "B",
    explanation: "善于推理、归纳的能力属于逻辑数学智能。",
  },
  {
    id: 250,
    type: "single",
    question: "AI系统学习和训练的前提是拥有足够的?",
    options: ["算力", "算法", "数据", "硬件"],
    answer: "C",
    explanation: "数据是AI系统学习和训练的前提。",
  },
  {
    id: 251,
    type: "single",
    question: "影响人工智能模型应用能力的核心因素是?",
    options: ["计算能力", "数据量", "标注质量", "模型大小"],
    answer: "A",
    explanation: "计算能力是影响模型应用能力的核心因素。",
  },
  {
    id: 252,
    type: "single",
    question: "不需要任何标注数据，让模型自主发现数据规律的是?",
    options: ["监督学习", "无监督学习", "半监督学习", "强化学习"],
    answer: "B",
    explanation: "无监督学习不需要标注数据，让模型自主发现数据规律。",
  },
  {
    id: 253,
    type: "single",
    question: "让模型动态关注输入数据关键部分的计算模型是?",
    options: ["损失函数", "注意力机制", "激活函数", "聚合函数"],
    answer: "B",
    explanation: "注意力机制让模型动态关注输入数据的关键部分。",
  },
  {
    id: 254,
    type: "single",
    question: "Transformer架构的核心是?",
    options: ["卷积层", "循环层", "自注意力机制", "池化层"],
    answer: "C",
    explanation: "Transformer架构的核心是自注意力机制。",
  },
  {
    id: 255,
    type: "single",
    question: "预测股票价格这类连续数值的任务属于?",
    options: ["分类", "回归", "聚类", "关联分析"],
    answer: "B",
    explanation: "预测连续数值的任务属于回归。",
  },
  {
    id: 256,
    type: "single",
    question: "识别手写数字这类离散类别预测的任务是?",
    options: ["分类", "回归", "降维", "聚类"],
    answer: "A",
    explanation: "识别手写数字属于分类任务。",
  },
  {
    id: 257,
    type: "single",
    question: "强化学习中，智能体学习的目标是找到?",
    options: ["最优动作", "最优奖励", "最优策略", "最优环境"],
    answer: "C",
    explanation: "强化学习中，智能体学习的目标是找到最优策略。",
  },
  {
    id: 258,
    type: "single",
    question: "损失函数的数值越小，说明模型的?",
    options: ["拟合效果越好", "拟合效果越差", "计算速度越快", "计算速度越慢"],
    answer: "A",
    explanation:
      "损失函数值越小，说明模型预测结果与真实结果越接近，拟合效果越好。",
  },
  {
    id: 259,
    type: "single",
    question: "模型训练阶段，用于评估模型初步效果的是?",
    options: ["新数据", "测试集", "验证集", "训练集"],
    answer: "C",
    explanation: "验证集用于训练阶段评估模型初步效果，调整超参数。",
  },
  {
    id: 260,
    type: "single",
    question: "模型正式上线前，最终验证效果的数据集是?",
    options: ["训练集", "验证集", "测试集", "标注集"],
    answer: "C",
    explanation: "测试集用于模型正式上线前的最终验证。",
  },
  {
    id: 261,
    type: "single",
    question: "混淆矩阵中，TN代表的是?",
    options: ["真正类", "假正类", "真负类", "假负类"],
    answer: "C",
    explanation: "TN（True Negative）代表真负类。",
  },
  {
    id: 262,
    type: "single",
    question: "特征工程的作用是为了让模型更好地?",
    options: ["存储数据", "理解和利用数据", "生成数据", "加密数据"],
    answer: "B",
    explanation: "特征工程的作用是让模型更好地理解和利用数据。",
  },
  {
    id: 263,
    type: "single",
    question: "数据清洗的操作不包括?",
    options: ["去除重复值", "填补缺失值", "去除异常值", "增加数据量"],
    answer: "D",
    explanation: "增加数据量是数据增强操作，不是数据清洗操作。",
  },
  {
    id: 264,
    type: "single",
    question: "下列关于人工智能的描述，错误的是?",
    options: [
      "是一门技术科学",
      "旨在实现人类智能的计算机模拟",
      "就是自动化生产线",
      "包含多个研究方向",
    ],
    answer: "C",
    explanation: "人工智能不仅仅是自动化生产线，而是更广泛的技术科学领域。",
  },
  {
    id: 265,
    type: "single",
    question: "深度学习隶属于以下哪个领域?",
    options: ["机器学习", "计算机网络", "软件工程", "硬件工程"],
    answer: "A",
    explanation: "深度学习是机器学习的一个分支领域。",
  },
  {
    id: 266,
    type: "single",
    question: "人工智能的诞生阶段是20世纪?",
    options: ["30-40年代", "40-50年代", "60-70年代", "70-80年代"],
    answer: "B",
    explanation: "人工智能诞生于20世纪40-50年代。",
  },
  {
    id: 267,
    type: "single",
    question: "大数据5V特征中，不包含以下哪个选项?",
    options: ["Veracity", "Value", "Valley", "Variety"],
    answer: "C",
    explanation: "Valley不属于大数据的5V特征。",
  },
  {
    id: 268,
    type: "single",
    question: "AlphaGo的核心技术不属于?",
    options: ["强化学习", "深度学习", "专家系统", "蒙特卡洛树搜索"],
    answer: "C",
    explanation: "AlphaGo的核心技术不包括专家系统。",
  },
  {
    id: 269,
    type: "single",
    question: "以下属于监督学习任务的是?",
    options: ["聚类", "分类", "关联规则挖掘", "降维"],
    answer: "B",
    explanation: "分类是监督学习的典型任务。",
  },
  {
    id: 270,
    type: "single",
    question: "图灵测试主要用于判断机器是否具备?",
    options: ["计算能力", "存储能力", "人类智能", "硬件性能"],
    answer: "C",
    explanation: "图灵测试用于判断机器是否具备人类智能。",
  },
  {
    id: 271,
    type: "single",
    question: "数据清洗的主要目的不包括?",
    options: ["提高数据质量", "保证数据一致性", "增加数据量", "提升数据完整性"],
    answer: "C",
    explanation: "增加数据量不是数据清洗的目的，是数据增强的目的。",
  },
  {
    id: 272,
    type: "single",
    question: "以下属于脏数据的是?",
    options: [
      "格式统一的准确数据",
      "无缺失的最新数据",
      "人为标注错误的数据",
      "规范的结构化数据",
    ],
    answer: "C",
    explanation: "人为标注错误的数据属于脏数据。",
  },
  {
    id: 273,
    type: "single",
    question: "数据整理的核心目标是让数据?",
    options: ["科学化、系统化", "数量更多", "格式更复杂", "更难被模型识别"],
    answer: "A",
    explanation: "数据整理的核心目标是让数据科学化、系统化。",
  },
  {
    id: 274,
    type: "single",
    question: "筛选出销量>100的商品后求和，属于?",
    options: ["基本统计汇总", "分组汇总", "条件汇总", "随机汇总"],
    answer: "C",
    explanation: "先筛选条件再求和，属于条件汇总。",
  },
  {
    id: 275,
    type: "single",
    question: "下列函数中，属于聚合函数的是?",
    options: ["sort", "min", "group", "filter"],
    answer: "B",
    explanation: "min是聚合函数，用于求最小值。",
  },
  {
    id: 276,
    type: "single",
    question: "常用的数据去重方法不包括?",
    options: ["排序算法", "哈希算法", "特征向量", "文本翻译"],
    answer: "D",
    explanation: "文本翻译不用于数据去重操作。",
  },
  {
    id: 277,
    type: "single",
    question: "图像特征统计中，常用的方法是?",
    options: ["文本归一化", "均值、方差", "去除重复文本", "处理缺失值"],
    answer: "B",
    explanation: "均值、方差是图像特征统计的常用方法。",
  },
  {
    id: 278,
    type: "single",
    question: "文本数据整理中，必须进行的操作是?",
    options: ["文本翻译", "去除重复文本", "语音转换", "图像匹配"],
    answer: "B",
    explanation: "去除重复文本是文本数据整理的基本操作。",
  },
  {
    id: 279,
    type: "single",
    question: "智能系统通过视觉、听觉感知环境，体现了其?",
    options: ["感知能力", "认知能力", "执行能力", "学习能力"],
    answer: "A",
    explanation: "感知环境属于智能系统的感知能力。",
  },
  {
    id: 280,
    type: "single",
    question: "智能系统的执行功能主要负责?",
    options: [
      "感知外界信息",
      "分析和判断信息",
      "根据决策做出动作",
      "存储各类信息",
    ],
    answer: "C",
    explanation: "执行功能负责根据决策做出相应的动作。",
  },
  {
    id: 281,
    type: "judge",
    question: "LabelImg支持YOLO格式和Pascal VOC格式的导出。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "LabelImg确实支持YOLO和Pascal VOC两种格式的导出。",
  },
  {
    id: 282,
    type: "judge",
    question: "数据标注的速度比质量更重要。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "数据标注的质量比速度更重要，低质量标注会影响模型训练效果。",
  },
  {
    id: 283,
    type: "judge",
    question: "Doccano可以用于标注文本中的实体关系。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "Doccano支持文本实体关系标注。",
  },
  {
    id: 284,
    type: "judge",
    question: "图像重采样会改变图像的分辨率。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "图像重采样确实会改变图像的尺寸和分辨率。",
  },
  {
    id: 285,
    type: "judge",
    question: "标注完成后，不需要检查标注文件的格式。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "标注完成后需要检查格式，确保与模型要求匹配。",
  },
  {
    id: 286,
    type: "judge",
    question: "Praat只能用于音频标注，不能进行音频分析。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation:
      "Praat不仅可以进行音频标注，还能进行频谱分析、基频提取等音频分析。",
  },
  {
    id: 287,
    type: "judge",
    question: "多边形标注可以精准框选不规则形状的目标。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "多边形标注适合标注不规则形状的目标，可以实现精准框选。",
  },
  {
    id: 288,
    type: "judge",
    question: "文本标注中，同一文本只能标注一种实体类型。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "同一文本可以标注多种实体类型，如人名、地名、组织机构名等。",
  },
  {
    id: 289,
    type: "judge",
    question: "数据增强和图像重采样是同一类操作。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation:
      "数据增强是扩充数据集的方法，图像重采样是改变图像尺寸的方法，目的不同。",
  },
  {
    id: 290,
    type: "judge",
    question: "LabelMe中，标注形状可以随意拖动和修改。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "在LabelMe中，标注形状可以被选中后拖动控制点进行修改。",
  },
  {
    id: 291,
    type: "judge",
    question: "达特茅斯会议标志着人工智能学科的正式诞生。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "1956年的达特茅斯会议被公认为人工智能学科的诞生标志。",
  },
  {
    id: 292,
    type: "judge",
    question: "人工智能训练师仅有数据标注员一个工种。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation:
      "人工智能训练师包含数据标注员和算法工程师（或算法测试员）等工种。",
  },
  {
    id: 293,
    type: "judge",
    question: "大数据的5V特征包括Volume、Variety、Velocity、Value、Veracity。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "大数据的5V特征确实包括这五个方面。",
  },
  {
    id: 294,
    type: "judge",
    question: "强人工智能和超人工智能目前均未实现大规模应用。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "强人工智能和超人工智能目前都处于研究阶段，未实现大规模应用。",
  },
  {
    id: 295,
    type: "judge",
    question: "人类九大智能中的自然智能是指思考宇宙终极问题的能力。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation:
      "自然智能是指识别和分类自然界中物体的能力，不是思考宇宙终极问题的能力。",
  },
  {
    id: 296,
    type: "judge",
    question: "算力决定了人工智能模型的训练速度和复杂度。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "算力是影响模型训练速度和复杂度的重要因素。",
  },
  {
    id: 297,
    type: "judge",
    question: "半监督学习是指全部数据都进行标注的学习方式。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "半监督学习是部分数据标注、部分数据未标注的学习方式。",
  },
  {
    id: 298,
    type: "judge",
    question: "注意力机制能帮助大模型更好地理解上下文语义。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "注意力机制确实能帮助模型更好地理解上下文语义关系。",
  },
  {
    id: 299,
    type: "judge",
    question: "损失函数是模型参数优化的重要依据。",
    options: ["正确", "错误"],
    answer: "正确",
    explanation: "损失函数是模型训练中参数优化的依据。",
  },
  {
    id: 300,
    type: "judge",
    question: "特征工程是机器学习流程中可有可无的步骤。",
    options: ["正确", "错误"],
    answer: "错误",
    explanation: "特征工程是机器学习流程中非常重要且必要的步骤。",
  },
];

export default questionBank;
